### ISSUE TITLE
获取类字段Field时，能否包含父类公共字段？

### ISSUE THREAD

**Issue by wangyaping9521** [luo-zhan/Transformer#6]
如图所示，通常一些公共字段：创建人、更新人均定义到基类中的，此时需要对基类的信息进行转换。

![image](https://github.com/luo-zhan/Transformer/assets/44017939/ba9639e9-9c05-4fd0-9cda-55b41f7e173a)

**Comment by luo-zhan** [comment]
感谢反馈，v2.1.0版已支持

**Comment by wangyaping9521** [comment]
![image](https://github.com/luo-zhan/Transformer/assets/44017939/72e92c81-fee0-485d-8ae7-5020770e9b86)

![image](https://github.com/luo-zhan/Transformer/assets/44017939/3eb57a1b-ab03-4018-8b58-e14f4766f055)

新版本缺少这个依赖没有发布。

**Comment by luo-zhan** [comment]
> ![image](https://user-images.githubusercontent.com/44017939/252831725-72e92c81-fee0-485d-8ae7-5020770e9b86.png)
> 
> ![image](https://user-images.githubusercontent.com/44017939/252831786-3eb57a1b-ab03-4018-8b58-e14f4766f055.png)
> 
> 新版本缺少这个依赖没有发布。

中央仓库已经有了，如果是镜像仓库可能会有点延迟
