### ISSUE TITLE
我将demo移至我的测试项目，transform失败。

### ISSUE THREAD

**Issue by mulanqishi** [luo-zhan/Transformer#8]
整个拷贝了demo 的所有文件，只是我的项目是其他domain地址。启动测试的时候transform失败，所有类型的都失败了，会是什么原因。我找了一整天原因，没有结果。

**Comment by luo-zhan** [comment]
抱歉，刚看到issues。提供的信息有限，没法帮你判断原因呢。

你按照下面步骤试试：
1. 先clone项目，试着跑一下demo的application，按照`StudentController`里的接口注释中的提示验证效果。

![image](https://github.com/luo-zhan/Transformer/assets/16471200/38a7ca6f-caf6-47f7-8959-3dd3b3e3eab3)

2. 如果没问题，在自己的测试项目中检查pom依赖和代码是否拷贝完整，然后启动项目后在`TransformAspect`类上断点：

![image](https://github.com/luo-zhan/Transformer/assets/16471200/9ceefb13-5f34-44de-b03d-2dd5ead99e36)
